collision_monitor:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_raw"
    cmd_vel_out_topic: "cmd_vel_raw2"
    transform_tolerance: 0.5
    source_timeout: 5.0
    stop_pub_timeout: 2.0
    # Polygons represent zone around the robot for "stop" and "slowdown" action types,
    # and robot footprint for "approach" action type.
    # Footprint could be "polygon" type with dynamically set footprint from footprint_topic
    # or "circle" type with static footprint set by radius. "footprint_topic" parameter
    # to be ignored in circular case.
    polygons: ["PolygonStop", "PolygonSlow", "PolygonSlow2", "FootprintApproach"]
    PolygonStop:
      type: "polygon"
      points: [0.2, 0.2, 0.2, -0.2, -0.2, -0.2, -0.2, 0.2]
      action_type: "stop"
      max_points: 3
      visualize: True
      activate: True
      polygon_pub_topic: "polygon_stop"
    PolygonSlow:
      type: "polygon"
      points: [0.6, 0.6, 0.6, -0.6, -0.6, -0.6, -0.6, 0.6]
      action_type: "slowdown"
      max_points: 3
      slowdown_ratio: 0.3
      visualize: True
      activate: True
      polygon_pub_topic: "polygon_slowdown"
    PolygonSlow2:
      type: "polygon"
      points: [0.8, 0.8, 0.8, -0.8, -0.8, -0.8, -0.8, 0.8]
      action_type: "slowdown"
      max_points: 3
      slowdown_ratio: 0.1
      visualize: True
      activate: False
      polygon_pub_topic: "polygon_slowdown2"
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "/local_costmap/published_footprint"
      time_before_collision: 2.0
      simulation_time_step: 0.1
      max_points: 5
      activate: True
      visualize: False
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/scan"
    pointcloud:
      type: "pointcloud"
      topic: "/intel_realsense_r200_depth/points"
      min_height: 0.1
      max_height: 0.5
