ekf_filter_node:
    ros__parameters:
        frequency: 50.0
        two_d_mode: true
        publish_tf: true
 
        odom_model_type: omni-corrected
        odom_alpha1: 0.005
        odom_alpha2: 0.005
        odom_alpha3: 0.01
        odom_alpha4: 0.005
        odom_alpha5: 0.005
        transform_tolerance: 0.2
        save_pose_rate: 0.5
        kld_err: 0.05
        kld_z: 0.99

        map_frame: map             
        odom_frame: odom            
        base_link_frame: base_footprint 
        world_frame: odom 

        #x     , y     , z,
        #roll  , pitch , yaw,
        #vx    , vy    , vz,
        #vroll , vpitch, vyaw,
        #ax    , ay    , az
        odom0: odom/unfiltered
        odom0_config: [false, false, false,
                       false, false, false,
                       true, true, false,
                       false, false, true,
                       false, false, false]

        imu0: imu/data
        imu0_config: [true, true, true,
                      false, false, true,
                      false, false, false,
                      false, false, true,
                      false, false, false]


        #odom0: odom/unfiltered
        #odom0_config: [true, true, false,
        #               false, false, true,
        #               true, true, false,
        #               false, false, true,
        #               false, false, false]

        #imu0: demo/imu
        #imu0_config: [false, false, false,
        #              true,  true,  true,
        #              false, false, false,
        #              false, false, false,
        #              false, false, false]
